#!/usr/bin/env ansible-playbook
---
- hosts: all # change this if you want to add more hosts.
  #remote_user: root
  become_method: sudo
  
  tasks:
  - name: Install Git
    package: name=git state=installed
    become: yes

  - name: install the 'Development tools' package group
    package: name="@Development tools" state=present
    when:  ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
    become: yes
    
  - name: Install the 'build-essential' meta package
    package: name="build-essential" state=present
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    become: yes

  - name: Add Node.js and Yarn repositories (Fedora/RHEL/CentOS)
    command: curl -sL https://rpm.nodesource.com/setup_12.x | bash - && curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
    when:  ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'
    become: yes

  - name: Add Node.js and Yarn repositories (Debian/Ubuntu)
    command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    become: yes

  - name: Install yarn
    package: name=yarn state=installed
    become: yes
    become_method: sudo

  - name: Install Node.js
    package: name=nodejs state=installed
    become: yes
    become_method: sudo

  - name: Install net-tools
    package: name=net-tools state=installed
    become: yes
    become_method: sudo

  - name: Install OpenSSL
    package: name=openssl state=installed
    become: yes
    become_method: sudo

  - name: Create directory
    file: path=/tmp/code-server state=directory owner={{ansible_user_id}}
    become: yes

  - name: Clone code-server
    git: repo=https://github.com/codercom/code-server dest=/tmp/code-server
    become: yes

  - name: Build and Install code-server
    command: chdir=/tmp/code-server yarn && yarn build 1.39.2 ansible && yarn binary 1.39.2 ansible && chmod -R 755 release/*-x86_64 && cp -Rf release/*-x86_64 /usr/bin/code-server
    become: yes
  
